// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Find(arg1) {
  return window['go']['backend']['Data']['Find'](arg1);
}

export function OnStartup(arg1) {
  return window['go']['backend']['Data']['OnStartup'](arg1);
}
