// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function Find(arg1:backend.FindParam):Promise<backend.FindResult>;

export function OnStartup(arg1:context.Context):Promise<void>;
