// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newBaseFieldMapping(db *gorm.DB, opts ...gen.DOOption) baseFieldMapping {
	_baseFieldMapping := baseFieldMapping{}

	_baseFieldMapping.baseFieldMappingDo.UseDB(db, opts...)
	_baseFieldMapping.baseFieldMappingDo.UseModel(&model.BaseFieldMapping{})

	tableName := _baseFieldMapping.baseFieldMappingDo.TableName()
	_baseFieldMapping.ALL = field.NewAsterisk(tableName)
	_baseFieldMapping.ItemTypeID = field.NewInt32(tableName, "itemTypeID")
	_baseFieldMapping.BaseFieldID = field.NewInt32(tableName, "baseFieldID")
	_baseFieldMapping.FieldID = field.NewInt32(tableName, "fieldID")

	_baseFieldMapping.fillFieldMap()

	return _baseFieldMapping
}

type baseFieldMapping struct {
	baseFieldMappingDo baseFieldMappingDo

	ALL         field.Asterisk
	ItemTypeID  field.Int32
	BaseFieldID field.Int32
	FieldID     field.Int32

	fieldMap map[string]field.Expr
}

func (b baseFieldMapping) Table(newTableName string) *baseFieldMapping {
	b.baseFieldMappingDo.UseTable(newTableName)
	return b.updateTableName(newTableName)
}

func (b baseFieldMapping) As(alias string) *baseFieldMapping {
	b.baseFieldMappingDo.DO = *(b.baseFieldMappingDo.As(alias).(*gen.DO))
	return b.updateTableName(alias)
}

func (b *baseFieldMapping) updateTableName(table string) *baseFieldMapping {
	b.ALL = field.NewAsterisk(table)
	b.ItemTypeID = field.NewInt32(table, "itemTypeID")
	b.BaseFieldID = field.NewInt32(table, "baseFieldID")
	b.FieldID = field.NewInt32(table, "fieldID")

	b.fillFieldMap()

	return b
}

func (b *baseFieldMapping) WithContext(ctx context.Context) *baseFieldMappingDo {
	return b.baseFieldMappingDo.WithContext(ctx)
}

func (b baseFieldMapping) TableName() string { return b.baseFieldMappingDo.TableName() }

func (b baseFieldMapping) Alias() string { return b.baseFieldMappingDo.Alias() }

func (b baseFieldMapping) Columns(cols ...field.Expr) gen.Columns {
	return b.baseFieldMappingDo.Columns(cols...)
}

func (b *baseFieldMapping) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := b.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (b *baseFieldMapping) fillFieldMap() {
	b.fieldMap = make(map[string]field.Expr, 3)
	b.fieldMap["itemTypeID"] = b.ItemTypeID
	b.fieldMap["baseFieldID"] = b.BaseFieldID
	b.fieldMap["fieldID"] = b.FieldID
}

func (b baseFieldMapping) clone(db *gorm.DB) baseFieldMapping {
	b.baseFieldMappingDo.ReplaceConnPool(db.Statement.ConnPool)
	return b
}

func (b baseFieldMapping) replaceDB(db *gorm.DB) baseFieldMapping {
	b.baseFieldMappingDo.ReplaceDB(db)
	return b
}

type baseFieldMappingDo struct{ gen.DO }

func (b baseFieldMappingDo) Debug() *baseFieldMappingDo {
	return b.withDO(b.DO.Debug())
}

func (b baseFieldMappingDo) WithContext(ctx context.Context) *baseFieldMappingDo {
	return b.withDO(b.DO.WithContext(ctx))
}

func (b baseFieldMappingDo) ReadDB() *baseFieldMappingDo {
	return b.Clauses(dbresolver.Read)
}

func (b baseFieldMappingDo) WriteDB() *baseFieldMappingDo {
	return b.Clauses(dbresolver.Write)
}

func (b baseFieldMappingDo) Session(config *gorm.Session) *baseFieldMappingDo {
	return b.withDO(b.DO.Session(config))
}

func (b baseFieldMappingDo) Clauses(conds ...clause.Expression) *baseFieldMappingDo {
	return b.withDO(b.DO.Clauses(conds...))
}

func (b baseFieldMappingDo) Returning(value interface{}, columns ...string) *baseFieldMappingDo {
	return b.withDO(b.DO.Returning(value, columns...))
}

func (b baseFieldMappingDo) Not(conds ...gen.Condition) *baseFieldMappingDo {
	return b.withDO(b.DO.Not(conds...))
}

func (b baseFieldMappingDo) Or(conds ...gen.Condition) *baseFieldMappingDo {
	return b.withDO(b.DO.Or(conds...))
}

func (b baseFieldMappingDo) Select(conds ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.Select(conds...))
}

func (b baseFieldMappingDo) Where(conds ...gen.Condition) *baseFieldMappingDo {
	return b.withDO(b.DO.Where(conds...))
}

func (b baseFieldMappingDo) Order(conds ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.Order(conds...))
}

func (b baseFieldMappingDo) Distinct(cols ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.Distinct(cols...))
}

func (b baseFieldMappingDo) Omit(cols ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.Omit(cols...))
}

func (b baseFieldMappingDo) Join(table schema.Tabler, on ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.Join(table, on...))
}

func (b baseFieldMappingDo) LeftJoin(table schema.Tabler, on ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.LeftJoin(table, on...))
}

func (b baseFieldMappingDo) RightJoin(table schema.Tabler, on ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.RightJoin(table, on...))
}

func (b baseFieldMappingDo) Group(cols ...field.Expr) *baseFieldMappingDo {
	return b.withDO(b.DO.Group(cols...))
}

func (b baseFieldMappingDo) Having(conds ...gen.Condition) *baseFieldMappingDo {
	return b.withDO(b.DO.Having(conds...))
}

func (b baseFieldMappingDo) Limit(limit int) *baseFieldMappingDo {
	return b.withDO(b.DO.Limit(limit))
}

func (b baseFieldMappingDo) Offset(offset int) *baseFieldMappingDo {
	return b.withDO(b.DO.Offset(offset))
}

func (b baseFieldMappingDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *baseFieldMappingDo {
	return b.withDO(b.DO.Scopes(funcs...))
}

func (b baseFieldMappingDo) Unscoped() *baseFieldMappingDo {
	return b.withDO(b.DO.Unscoped())
}

func (b baseFieldMappingDo) Create(values ...*model.BaseFieldMapping) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Create(values)
}

func (b baseFieldMappingDo) CreateInBatches(values []*model.BaseFieldMapping, batchSize int) error {
	return b.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (b baseFieldMappingDo) Save(values ...*model.BaseFieldMapping) error {
	if len(values) == 0 {
		return nil
	}
	return b.DO.Save(values)
}

func (b baseFieldMappingDo) First() (*model.BaseFieldMapping, error) {
	if result, err := b.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.BaseFieldMapping), nil
	}
}

func (b baseFieldMappingDo) Take() (*model.BaseFieldMapping, error) {
	if result, err := b.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.BaseFieldMapping), nil
	}
}

func (b baseFieldMappingDo) Last() (*model.BaseFieldMapping, error) {
	if result, err := b.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.BaseFieldMapping), nil
	}
}

func (b baseFieldMappingDo) Find() ([]*model.BaseFieldMapping, error) {
	result, err := b.DO.Find()
	return result.([]*model.BaseFieldMapping), err
}

func (b baseFieldMappingDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.BaseFieldMapping, err error) {
	buf := make([]*model.BaseFieldMapping, 0, batchSize)
	err = b.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (b baseFieldMappingDo) FindInBatches(result *[]*model.BaseFieldMapping, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return b.DO.FindInBatches(result, batchSize, fc)
}

func (b baseFieldMappingDo) Attrs(attrs ...field.AssignExpr) *baseFieldMappingDo {
	return b.withDO(b.DO.Attrs(attrs...))
}

func (b baseFieldMappingDo) Assign(attrs ...field.AssignExpr) *baseFieldMappingDo {
	return b.withDO(b.DO.Assign(attrs...))
}

func (b baseFieldMappingDo) Joins(fields ...field.RelationField) *baseFieldMappingDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Joins(_f))
	}
	return &b
}

func (b baseFieldMappingDo) Preload(fields ...field.RelationField) *baseFieldMappingDo {
	for _, _f := range fields {
		b = *b.withDO(b.DO.Preload(_f))
	}
	return &b
}

func (b baseFieldMappingDo) FirstOrInit() (*model.BaseFieldMapping, error) {
	if result, err := b.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.BaseFieldMapping), nil
	}
}

func (b baseFieldMappingDo) FirstOrCreate() (*model.BaseFieldMapping, error) {
	if result, err := b.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.BaseFieldMapping), nil
	}
}

func (b baseFieldMappingDo) FindByPage(offset int, limit int) (result []*model.BaseFieldMapping, count int64, err error) {
	result, err = b.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = b.Offset(-1).Limit(-1).Count()
	return
}

func (b baseFieldMappingDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = b.Count()
	if err != nil {
		return
	}

	err = b.Offset(offset).Limit(limit).Scan(result)
	return
}

func (b baseFieldMappingDo) Scan(result interface{}) (err error) {
	return b.DO.Scan(result)
}

func (b baseFieldMappingDo) Delete(models ...*model.BaseFieldMapping) (result gen.ResultInfo, err error) {
	return b.DO.Delete(models)
}

func (b *baseFieldMappingDo) withDO(do gen.Dao) *baseFieldMappingDo {
	b.DO = *do.(*gen.DO)
	return b
}
