// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newCollectionRelation(db *gorm.DB, opts ...gen.DOOption) collectionRelation {
	_collectionRelation := collectionRelation{}

	_collectionRelation.collectionRelationDo.UseDB(db, opts...)
	_collectionRelation.collectionRelationDo.UseModel(&model.CollectionRelation{})

	tableName := _collectionRelation.collectionRelationDo.TableName()
	_collectionRelation.ALL = field.NewAsterisk(tableName)
	_collectionRelation.CollectionID = field.NewInt32(tableName, "collectionID")
	_collectionRelation.PredicateID = field.NewInt32(tableName, "predicateID")
	_collectionRelation.Object = field.NewString(tableName, "object")

	_collectionRelation.fillFieldMap()

	return _collectionRelation
}

type collectionRelation struct {
	collectionRelationDo collectionRelationDo

	ALL          field.Asterisk
	CollectionID field.Int32
	PredicateID  field.Int32
	Object       field.String

	fieldMap map[string]field.Expr
}

func (c collectionRelation) Table(newTableName string) *collectionRelation {
	c.collectionRelationDo.UseTable(newTableName)
	return c.updateTableName(newTableName)
}

func (c collectionRelation) As(alias string) *collectionRelation {
	c.collectionRelationDo.DO = *(c.collectionRelationDo.As(alias).(*gen.DO))
	return c.updateTableName(alias)
}

func (c *collectionRelation) updateTableName(table string) *collectionRelation {
	c.ALL = field.NewAsterisk(table)
	c.CollectionID = field.NewInt32(table, "collectionID")
	c.PredicateID = field.NewInt32(table, "predicateID")
	c.Object = field.NewString(table, "object")

	c.fillFieldMap()

	return c
}

func (c *collectionRelation) WithContext(ctx context.Context) *collectionRelationDo {
	return c.collectionRelationDo.WithContext(ctx)
}

func (c collectionRelation) TableName() string { return c.collectionRelationDo.TableName() }

func (c collectionRelation) Alias() string { return c.collectionRelationDo.Alias() }

func (c collectionRelation) Columns(cols ...field.Expr) gen.Columns {
	return c.collectionRelationDo.Columns(cols...)
}

func (c *collectionRelation) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := c.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (c *collectionRelation) fillFieldMap() {
	c.fieldMap = make(map[string]field.Expr, 3)
	c.fieldMap["collectionID"] = c.CollectionID
	c.fieldMap["predicateID"] = c.PredicateID
	c.fieldMap["object"] = c.Object
}

func (c collectionRelation) clone(db *gorm.DB) collectionRelation {
	c.collectionRelationDo.ReplaceConnPool(db.Statement.ConnPool)
	return c
}

func (c collectionRelation) replaceDB(db *gorm.DB) collectionRelation {
	c.collectionRelationDo.ReplaceDB(db)
	return c
}

type collectionRelationDo struct{ gen.DO }

func (c collectionRelationDo) Debug() *collectionRelationDo {
	return c.withDO(c.DO.Debug())
}

func (c collectionRelationDo) WithContext(ctx context.Context) *collectionRelationDo {
	return c.withDO(c.DO.WithContext(ctx))
}

func (c collectionRelationDo) ReadDB() *collectionRelationDo {
	return c.Clauses(dbresolver.Read)
}

func (c collectionRelationDo) WriteDB() *collectionRelationDo {
	return c.Clauses(dbresolver.Write)
}

func (c collectionRelationDo) Session(config *gorm.Session) *collectionRelationDo {
	return c.withDO(c.DO.Session(config))
}

func (c collectionRelationDo) Clauses(conds ...clause.Expression) *collectionRelationDo {
	return c.withDO(c.DO.Clauses(conds...))
}

func (c collectionRelationDo) Returning(value interface{}, columns ...string) *collectionRelationDo {
	return c.withDO(c.DO.Returning(value, columns...))
}

func (c collectionRelationDo) Not(conds ...gen.Condition) *collectionRelationDo {
	return c.withDO(c.DO.Not(conds...))
}

func (c collectionRelationDo) Or(conds ...gen.Condition) *collectionRelationDo {
	return c.withDO(c.DO.Or(conds...))
}

func (c collectionRelationDo) Select(conds ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.Select(conds...))
}

func (c collectionRelationDo) Where(conds ...gen.Condition) *collectionRelationDo {
	return c.withDO(c.DO.Where(conds...))
}

func (c collectionRelationDo) Order(conds ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.Order(conds...))
}

func (c collectionRelationDo) Distinct(cols ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.Distinct(cols...))
}

func (c collectionRelationDo) Omit(cols ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.Omit(cols...))
}

func (c collectionRelationDo) Join(table schema.Tabler, on ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.Join(table, on...))
}

func (c collectionRelationDo) LeftJoin(table schema.Tabler, on ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.LeftJoin(table, on...))
}

func (c collectionRelationDo) RightJoin(table schema.Tabler, on ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.RightJoin(table, on...))
}

func (c collectionRelationDo) Group(cols ...field.Expr) *collectionRelationDo {
	return c.withDO(c.DO.Group(cols...))
}

func (c collectionRelationDo) Having(conds ...gen.Condition) *collectionRelationDo {
	return c.withDO(c.DO.Having(conds...))
}

func (c collectionRelationDo) Limit(limit int) *collectionRelationDo {
	return c.withDO(c.DO.Limit(limit))
}

func (c collectionRelationDo) Offset(offset int) *collectionRelationDo {
	return c.withDO(c.DO.Offset(offset))
}

func (c collectionRelationDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *collectionRelationDo {
	return c.withDO(c.DO.Scopes(funcs...))
}

func (c collectionRelationDo) Unscoped() *collectionRelationDo {
	return c.withDO(c.DO.Unscoped())
}

func (c collectionRelationDo) Create(values ...*model.CollectionRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Create(values)
}

func (c collectionRelationDo) CreateInBatches(values []*model.CollectionRelation, batchSize int) error {
	return c.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (c collectionRelationDo) Save(values ...*model.CollectionRelation) error {
	if len(values) == 0 {
		return nil
	}
	return c.DO.Save(values)
}

func (c collectionRelationDo) First() (*model.CollectionRelation, error) {
	if result, err := c.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionRelation), nil
	}
}

func (c collectionRelationDo) Take() (*model.CollectionRelation, error) {
	if result, err := c.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionRelation), nil
	}
}

func (c collectionRelationDo) Last() (*model.CollectionRelation, error) {
	if result, err := c.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionRelation), nil
	}
}

func (c collectionRelationDo) Find() ([]*model.CollectionRelation, error) {
	result, err := c.DO.Find()
	return result.([]*model.CollectionRelation), err
}

func (c collectionRelationDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.CollectionRelation, err error) {
	buf := make([]*model.CollectionRelation, 0, batchSize)
	err = c.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (c collectionRelationDo) FindInBatches(result *[]*model.CollectionRelation, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return c.DO.FindInBatches(result, batchSize, fc)
}

func (c collectionRelationDo) Attrs(attrs ...field.AssignExpr) *collectionRelationDo {
	return c.withDO(c.DO.Attrs(attrs...))
}

func (c collectionRelationDo) Assign(attrs ...field.AssignExpr) *collectionRelationDo {
	return c.withDO(c.DO.Assign(attrs...))
}

func (c collectionRelationDo) Joins(fields ...field.RelationField) *collectionRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Joins(_f))
	}
	return &c
}

func (c collectionRelationDo) Preload(fields ...field.RelationField) *collectionRelationDo {
	for _, _f := range fields {
		c = *c.withDO(c.DO.Preload(_f))
	}
	return &c
}

func (c collectionRelationDo) FirstOrInit() (*model.CollectionRelation, error) {
	if result, err := c.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionRelation), nil
	}
}

func (c collectionRelationDo) FirstOrCreate() (*model.CollectionRelation, error) {
	if result, err := c.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.CollectionRelation), nil
	}
}

func (c collectionRelationDo) FindByPage(offset int, limit int) (result []*model.CollectionRelation, count int64, err error) {
	result, err = c.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = c.Offset(-1).Limit(-1).Count()
	return
}

func (c collectionRelationDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = c.Count()
	if err != nil {
		return
	}

	err = c.Offset(offset).Limit(limit).Scan(result)
	return
}

func (c collectionRelationDo) Scan(result interface{}) (err error) {
	return c.DO.Scan(result)
}

func (c collectionRelationDo) Delete(models ...*model.CollectionRelation) (result gen.ResultInfo, err error) {
	return c.DO.Delete(models)
}

func (c *collectionRelationDo) withDO(do gen.Dao) *collectionRelationDo {
	c.DO = *do.(*gen.DO)
	return c
}
