// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newDeletedItem(db *gorm.DB, opts ...gen.DOOption) deletedItem {
	_deletedItem := deletedItem{}

	_deletedItem.deletedItemDo.UseDB(db, opts...)
	_deletedItem.deletedItemDo.UseModel(&model.DeletedItem{})

	tableName := _deletedItem.deletedItemDo.TableName()
	_deletedItem.ALL = field.NewAsterisk(tableName)
	_deletedItem.ItemID = field.NewInt32(tableName, "itemID")
	_deletedItem.DateDeleted = field.NewString(tableName, "dateDeleted")

	_deletedItem.fillFieldMap()

	return _deletedItem
}

type deletedItem struct {
	deletedItemDo deletedItemDo

	ALL         field.Asterisk
	ItemID      field.Int32
	DateDeleted field.String

	fieldMap map[string]field.Expr
}

func (d deletedItem) Table(newTableName string) *deletedItem {
	d.deletedItemDo.UseTable(newTableName)
	return d.updateTableName(newTableName)
}

func (d deletedItem) As(alias string) *deletedItem {
	d.deletedItemDo.DO = *(d.deletedItemDo.As(alias).(*gen.DO))
	return d.updateTableName(alias)
}

func (d *deletedItem) updateTableName(table string) *deletedItem {
	d.ALL = field.NewAsterisk(table)
	d.ItemID = field.NewInt32(table, "itemID")
	d.DateDeleted = field.NewString(table, "dateDeleted")

	d.fillFieldMap()

	return d
}

func (d *deletedItem) WithContext(ctx context.Context) *deletedItemDo {
	return d.deletedItemDo.WithContext(ctx)
}

func (d deletedItem) TableName() string { return d.deletedItemDo.TableName() }

func (d deletedItem) Alias() string { return d.deletedItemDo.Alias() }

func (d deletedItem) Columns(cols ...field.Expr) gen.Columns { return d.deletedItemDo.Columns(cols...) }

func (d *deletedItem) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := d.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (d *deletedItem) fillFieldMap() {
	d.fieldMap = make(map[string]field.Expr, 2)
	d.fieldMap["itemID"] = d.ItemID
	d.fieldMap["dateDeleted"] = d.DateDeleted
}

func (d deletedItem) clone(db *gorm.DB) deletedItem {
	d.deletedItemDo.ReplaceConnPool(db.Statement.ConnPool)
	return d
}

func (d deletedItem) replaceDB(db *gorm.DB) deletedItem {
	d.deletedItemDo.ReplaceDB(db)
	return d
}

type deletedItemDo struct{ gen.DO }

func (d deletedItemDo) Debug() *deletedItemDo {
	return d.withDO(d.DO.Debug())
}

func (d deletedItemDo) WithContext(ctx context.Context) *deletedItemDo {
	return d.withDO(d.DO.WithContext(ctx))
}

func (d deletedItemDo) ReadDB() *deletedItemDo {
	return d.Clauses(dbresolver.Read)
}

func (d deletedItemDo) WriteDB() *deletedItemDo {
	return d.Clauses(dbresolver.Write)
}

func (d deletedItemDo) Session(config *gorm.Session) *deletedItemDo {
	return d.withDO(d.DO.Session(config))
}

func (d deletedItemDo) Clauses(conds ...clause.Expression) *deletedItemDo {
	return d.withDO(d.DO.Clauses(conds...))
}

func (d deletedItemDo) Returning(value interface{}, columns ...string) *deletedItemDo {
	return d.withDO(d.DO.Returning(value, columns...))
}

func (d deletedItemDo) Not(conds ...gen.Condition) *deletedItemDo {
	return d.withDO(d.DO.Not(conds...))
}

func (d deletedItemDo) Or(conds ...gen.Condition) *deletedItemDo {
	return d.withDO(d.DO.Or(conds...))
}

func (d deletedItemDo) Select(conds ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.Select(conds...))
}

func (d deletedItemDo) Where(conds ...gen.Condition) *deletedItemDo {
	return d.withDO(d.DO.Where(conds...))
}

func (d deletedItemDo) Order(conds ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.Order(conds...))
}

func (d deletedItemDo) Distinct(cols ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.Distinct(cols...))
}

func (d deletedItemDo) Omit(cols ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.Omit(cols...))
}

func (d deletedItemDo) Join(table schema.Tabler, on ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.Join(table, on...))
}

func (d deletedItemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.LeftJoin(table, on...))
}

func (d deletedItemDo) RightJoin(table schema.Tabler, on ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.RightJoin(table, on...))
}

func (d deletedItemDo) Group(cols ...field.Expr) *deletedItemDo {
	return d.withDO(d.DO.Group(cols...))
}

func (d deletedItemDo) Having(conds ...gen.Condition) *deletedItemDo {
	return d.withDO(d.DO.Having(conds...))
}

func (d deletedItemDo) Limit(limit int) *deletedItemDo {
	return d.withDO(d.DO.Limit(limit))
}

func (d deletedItemDo) Offset(offset int) *deletedItemDo {
	return d.withDO(d.DO.Offset(offset))
}

func (d deletedItemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *deletedItemDo {
	return d.withDO(d.DO.Scopes(funcs...))
}

func (d deletedItemDo) Unscoped() *deletedItemDo {
	return d.withDO(d.DO.Unscoped())
}

func (d deletedItemDo) Create(values ...*model.DeletedItem) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Create(values)
}

func (d deletedItemDo) CreateInBatches(values []*model.DeletedItem, batchSize int) error {
	return d.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (d deletedItemDo) Save(values ...*model.DeletedItem) error {
	if len(values) == 0 {
		return nil
	}
	return d.DO.Save(values)
}

func (d deletedItemDo) First() (*model.DeletedItem, error) {
	if result, err := d.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedItem), nil
	}
}

func (d deletedItemDo) Take() (*model.DeletedItem, error) {
	if result, err := d.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedItem), nil
	}
}

func (d deletedItemDo) Last() (*model.DeletedItem, error) {
	if result, err := d.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedItem), nil
	}
}

func (d deletedItemDo) Find() ([]*model.DeletedItem, error) {
	result, err := d.DO.Find()
	return result.([]*model.DeletedItem), err
}

func (d deletedItemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.DeletedItem, err error) {
	buf := make([]*model.DeletedItem, 0, batchSize)
	err = d.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (d deletedItemDo) FindInBatches(result *[]*model.DeletedItem, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return d.DO.FindInBatches(result, batchSize, fc)
}

func (d deletedItemDo) Attrs(attrs ...field.AssignExpr) *deletedItemDo {
	return d.withDO(d.DO.Attrs(attrs...))
}

func (d deletedItemDo) Assign(attrs ...field.AssignExpr) *deletedItemDo {
	return d.withDO(d.DO.Assign(attrs...))
}

func (d deletedItemDo) Joins(fields ...field.RelationField) *deletedItemDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Joins(_f))
	}
	return &d
}

func (d deletedItemDo) Preload(fields ...field.RelationField) *deletedItemDo {
	for _, _f := range fields {
		d = *d.withDO(d.DO.Preload(_f))
	}
	return &d
}

func (d deletedItemDo) FirstOrInit() (*model.DeletedItem, error) {
	if result, err := d.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedItem), nil
	}
}

func (d deletedItemDo) FirstOrCreate() (*model.DeletedItem, error) {
	if result, err := d.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.DeletedItem), nil
	}
}

func (d deletedItemDo) FindByPage(offset int, limit int) (result []*model.DeletedItem, count int64, err error) {
	result, err = d.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = d.Offset(-1).Limit(-1).Count()
	return
}

func (d deletedItemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = d.Count()
	if err != nil {
		return
	}

	err = d.Offset(offset).Limit(limit).Scan(result)
	return
}

func (d deletedItemDo) Scan(result interface{}) (err error) {
	return d.DO.Scan(result)
}

func (d deletedItemDo) Delete(models ...*model.DeletedItem) (result gen.ResultInfo, err error) {
	return d.DO.Delete(models)
}

func (d *deletedItemDo) withDO(do gen.Dao) *deletedItemDo {
	d.DO = *do.(*gen.DO)
	return d
}
