// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newFulltextWord(db *gorm.DB, opts ...gen.DOOption) fulltextWord {
	_fulltextWord := fulltextWord{}

	_fulltextWord.fulltextWordDo.UseDB(db, opts...)
	_fulltextWord.fulltextWordDo.UseModel(&model.FulltextWord{})

	tableName := _fulltextWord.fulltextWordDo.TableName()
	_fulltextWord.ALL = field.NewAsterisk(tableName)
	_fulltextWord.WordID = field.NewInt32(tableName, "wordID")
	_fulltextWord.Word = field.NewString(tableName, "word")

	_fulltextWord.fillFieldMap()

	return _fulltextWord
}

type fulltextWord struct {
	fulltextWordDo fulltextWordDo

	ALL    field.Asterisk
	WordID field.Int32
	Word   field.String

	fieldMap map[string]field.Expr
}

func (f fulltextWord) Table(newTableName string) *fulltextWord {
	f.fulltextWordDo.UseTable(newTableName)
	return f.updateTableName(newTableName)
}

func (f fulltextWord) As(alias string) *fulltextWord {
	f.fulltextWordDo.DO = *(f.fulltextWordDo.As(alias).(*gen.DO))
	return f.updateTableName(alias)
}

func (f *fulltextWord) updateTableName(table string) *fulltextWord {
	f.ALL = field.NewAsterisk(table)
	f.WordID = field.NewInt32(table, "wordID")
	f.Word = field.NewString(table, "word")

	f.fillFieldMap()

	return f
}

func (f *fulltextWord) WithContext(ctx context.Context) *fulltextWordDo {
	return f.fulltextWordDo.WithContext(ctx)
}

func (f fulltextWord) TableName() string { return f.fulltextWordDo.TableName() }

func (f fulltextWord) Alias() string { return f.fulltextWordDo.Alias() }

func (f fulltextWord) Columns(cols ...field.Expr) gen.Columns {
	return f.fulltextWordDo.Columns(cols...)
}

func (f *fulltextWord) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := f.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (f *fulltextWord) fillFieldMap() {
	f.fieldMap = make(map[string]field.Expr, 2)
	f.fieldMap["wordID"] = f.WordID
	f.fieldMap["word"] = f.Word
}

func (f fulltextWord) clone(db *gorm.DB) fulltextWord {
	f.fulltextWordDo.ReplaceConnPool(db.Statement.ConnPool)
	return f
}

func (f fulltextWord) replaceDB(db *gorm.DB) fulltextWord {
	f.fulltextWordDo.ReplaceDB(db)
	return f
}

type fulltextWordDo struct{ gen.DO }

func (f fulltextWordDo) Debug() *fulltextWordDo {
	return f.withDO(f.DO.Debug())
}

func (f fulltextWordDo) WithContext(ctx context.Context) *fulltextWordDo {
	return f.withDO(f.DO.WithContext(ctx))
}

func (f fulltextWordDo) ReadDB() *fulltextWordDo {
	return f.Clauses(dbresolver.Read)
}

func (f fulltextWordDo) WriteDB() *fulltextWordDo {
	return f.Clauses(dbresolver.Write)
}

func (f fulltextWordDo) Session(config *gorm.Session) *fulltextWordDo {
	return f.withDO(f.DO.Session(config))
}

func (f fulltextWordDo) Clauses(conds ...clause.Expression) *fulltextWordDo {
	return f.withDO(f.DO.Clauses(conds...))
}

func (f fulltextWordDo) Returning(value interface{}, columns ...string) *fulltextWordDo {
	return f.withDO(f.DO.Returning(value, columns...))
}

func (f fulltextWordDo) Not(conds ...gen.Condition) *fulltextWordDo {
	return f.withDO(f.DO.Not(conds...))
}

func (f fulltextWordDo) Or(conds ...gen.Condition) *fulltextWordDo {
	return f.withDO(f.DO.Or(conds...))
}

func (f fulltextWordDo) Select(conds ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.Select(conds...))
}

func (f fulltextWordDo) Where(conds ...gen.Condition) *fulltextWordDo {
	return f.withDO(f.DO.Where(conds...))
}

func (f fulltextWordDo) Order(conds ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.Order(conds...))
}

func (f fulltextWordDo) Distinct(cols ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.Distinct(cols...))
}

func (f fulltextWordDo) Omit(cols ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.Omit(cols...))
}

func (f fulltextWordDo) Join(table schema.Tabler, on ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.Join(table, on...))
}

func (f fulltextWordDo) LeftJoin(table schema.Tabler, on ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.LeftJoin(table, on...))
}

func (f fulltextWordDo) RightJoin(table schema.Tabler, on ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.RightJoin(table, on...))
}

func (f fulltextWordDo) Group(cols ...field.Expr) *fulltextWordDo {
	return f.withDO(f.DO.Group(cols...))
}

func (f fulltextWordDo) Having(conds ...gen.Condition) *fulltextWordDo {
	return f.withDO(f.DO.Having(conds...))
}

func (f fulltextWordDo) Limit(limit int) *fulltextWordDo {
	return f.withDO(f.DO.Limit(limit))
}

func (f fulltextWordDo) Offset(offset int) *fulltextWordDo {
	return f.withDO(f.DO.Offset(offset))
}

func (f fulltextWordDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *fulltextWordDo {
	return f.withDO(f.DO.Scopes(funcs...))
}

func (f fulltextWordDo) Unscoped() *fulltextWordDo {
	return f.withDO(f.DO.Unscoped())
}

func (f fulltextWordDo) Create(values ...*model.FulltextWord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Create(values)
}

func (f fulltextWordDo) CreateInBatches(values []*model.FulltextWord, batchSize int) error {
	return f.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (f fulltextWordDo) Save(values ...*model.FulltextWord) error {
	if len(values) == 0 {
		return nil
	}
	return f.DO.Save(values)
}

func (f fulltextWordDo) First() (*model.FulltextWord, error) {
	if result, err := f.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.FulltextWord), nil
	}
}

func (f fulltextWordDo) Take() (*model.FulltextWord, error) {
	if result, err := f.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.FulltextWord), nil
	}
}

func (f fulltextWordDo) Last() (*model.FulltextWord, error) {
	if result, err := f.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.FulltextWord), nil
	}
}

func (f fulltextWordDo) Find() ([]*model.FulltextWord, error) {
	result, err := f.DO.Find()
	return result.([]*model.FulltextWord), err
}

func (f fulltextWordDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.FulltextWord, err error) {
	buf := make([]*model.FulltextWord, 0, batchSize)
	err = f.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (f fulltextWordDo) FindInBatches(result *[]*model.FulltextWord, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return f.DO.FindInBatches(result, batchSize, fc)
}

func (f fulltextWordDo) Attrs(attrs ...field.AssignExpr) *fulltextWordDo {
	return f.withDO(f.DO.Attrs(attrs...))
}

func (f fulltextWordDo) Assign(attrs ...field.AssignExpr) *fulltextWordDo {
	return f.withDO(f.DO.Assign(attrs...))
}

func (f fulltextWordDo) Joins(fields ...field.RelationField) *fulltextWordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Joins(_f))
	}
	return &f
}

func (f fulltextWordDo) Preload(fields ...field.RelationField) *fulltextWordDo {
	for _, _f := range fields {
		f = *f.withDO(f.DO.Preload(_f))
	}
	return &f
}

func (f fulltextWordDo) FirstOrInit() (*model.FulltextWord, error) {
	if result, err := f.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.FulltextWord), nil
	}
}

func (f fulltextWordDo) FirstOrCreate() (*model.FulltextWord, error) {
	if result, err := f.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.FulltextWord), nil
	}
}

func (f fulltextWordDo) FindByPage(offset int, limit int) (result []*model.FulltextWord, count int64, err error) {
	result, err = f.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = f.Offset(-1).Limit(-1).Count()
	return
}

func (f fulltextWordDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = f.Count()
	if err != nil {
		return
	}

	err = f.Offset(offset).Limit(limit).Scan(result)
	return
}

func (f fulltextWordDo) Scan(result interface{}) (err error) {
	return f.DO.Scan(result)
}

func (f fulltextWordDo) Delete(models ...*model.FulltextWord) (result gen.ResultInfo, err error) {
	return f.DO.Delete(models)
}

func (f *fulltextWordDo) withDO(do gen.Dao) *fulltextWordDo {
	f.DO = *do.(*gen.DO)
	return f
}
