// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newItem(db *gorm.DB, opts ...gen.DOOption) item {
	_item := item{}

	_item.itemDo.UseDB(db, opts...)
	_item.itemDo.UseModel(&model.Item{})

	tableName := _item.itemDo.TableName()
	_item.ALL = field.NewAsterisk(tableName)
	_item.ItemID = field.NewInt32(tableName, "itemID")
	_item.ItemTypeID = field.NewInt32(tableName, "itemTypeID")
	_item.DateAdded = field.NewTime(tableName, "dateAdded")
	_item.DateModified = field.NewTime(tableName, "dateModified")
	_item.ClientDateModified = field.NewTime(tableName, "clientDateModified")
	_item.LibraryID = field.NewInt32(tableName, "libraryID")
	_item.Key = field.NewString(tableName, "key")
	_item.Version = field.NewInt32(tableName, "version")
	_item.Synced = field.NewInt32(tableName, "synced")

	_item.fillFieldMap()

	return _item
}

type item struct {
	itemDo itemDo

	ALL                field.Asterisk
	ItemID             field.Int32
	ItemTypeID         field.Int32
	DateAdded          field.Time
	DateModified       field.Time
	ClientDateModified field.Time
	LibraryID          field.Int32
	Key                field.String
	Version            field.Int32
	Synced             field.Int32

	fieldMap map[string]field.Expr
}

func (i item) Table(newTableName string) *item {
	i.itemDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i item) As(alias string) *item {
	i.itemDo.DO = *(i.itemDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *item) updateTableName(table string) *item {
	i.ALL = field.NewAsterisk(table)
	i.ItemID = field.NewInt32(table, "itemID")
	i.ItemTypeID = field.NewInt32(table, "itemTypeID")
	i.DateAdded = field.NewTime(table, "dateAdded")
	i.DateModified = field.NewTime(table, "dateModified")
	i.ClientDateModified = field.NewTime(table, "clientDateModified")
	i.LibraryID = field.NewInt32(table, "libraryID")
	i.Key = field.NewString(table, "key")
	i.Version = field.NewInt32(table, "version")
	i.Synced = field.NewInt32(table, "synced")

	i.fillFieldMap()

	return i
}

func (i *item) WithContext(ctx context.Context) *itemDo { return i.itemDo.WithContext(ctx) }

func (i item) TableName() string { return i.itemDo.TableName() }

func (i item) Alias() string { return i.itemDo.Alias() }

func (i item) Columns(cols ...field.Expr) gen.Columns { return i.itemDo.Columns(cols...) }

func (i *item) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *item) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 9)
	i.fieldMap["itemID"] = i.ItemID
	i.fieldMap["itemTypeID"] = i.ItemTypeID
	i.fieldMap["dateAdded"] = i.DateAdded
	i.fieldMap["dateModified"] = i.DateModified
	i.fieldMap["clientDateModified"] = i.ClientDateModified
	i.fieldMap["libraryID"] = i.LibraryID
	i.fieldMap["key"] = i.Key
	i.fieldMap["version"] = i.Version
	i.fieldMap["synced"] = i.Synced
}

func (i item) clone(db *gorm.DB) item {
	i.itemDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i item) replaceDB(db *gorm.DB) item {
	i.itemDo.ReplaceDB(db)
	return i
}

type itemDo struct{ gen.DO }

func (i itemDo) Debug() *itemDo {
	return i.withDO(i.DO.Debug())
}

func (i itemDo) WithContext(ctx context.Context) *itemDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i itemDo) ReadDB() *itemDo {
	return i.Clauses(dbresolver.Read)
}

func (i itemDo) WriteDB() *itemDo {
	return i.Clauses(dbresolver.Write)
}

func (i itemDo) Session(config *gorm.Session) *itemDo {
	return i.withDO(i.DO.Session(config))
}

func (i itemDo) Clauses(conds ...clause.Expression) *itemDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i itemDo) Returning(value interface{}, columns ...string) *itemDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i itemDo) Not(conds ...gen.Condition) *itemDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i itemDo) Or(conds ...gen.Condition) *itemDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i itemDo) Select(conds ...field.Expr) *itemDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i itemDo) Where(conds ...gen.Condition) *itemDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i itemDo) Order(conds ...field.Expr) *itemDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i itemDo) Distinct(cols ...field.Expr) *itemDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i itemDo) Omit(cols ...field.Expr) *itemDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i itemDo) Join(table schema.Tabler, on ...field.Expr) *itemDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i itemDo) LeftJoin(table schema.Tabler, on ...field.Expr) *itemDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i itemDo) RightJoin(table schema.Tabler, on ...field.Expr) *itemDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i itemDo) Group(cols ...field.Expr) *itemDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i itemDo) Having(conds ...gen.Condition) *itemDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i itemDo) Limit(limit int) *itemDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i itemDo) Offset(offset int) *itemDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i itemDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *itemDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i itemDo) Unscoped() *itemDo {
	return i.withDO(i.DO.Unscoped())
}

func (i itemDo) Create(values ...*model.Item) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i itemDo) CreateInBatches(values []*model.Item, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i itemDo) Save(values ...*model.Item) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i itemDo) First() (*model.Item, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) Take() (*model.Item, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) Last() (*model.Item, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) Find() ([]*model.Item, error) {
	result, err := i.DO.Find()
	return result.([]*model.Item), err
}

func (i itemDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Item, err error) {
	buf := make([]*model.Item, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i itemDo) FindInBatches(result *[]*model.Item, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i itemDo) Attrs(attrs ...field.AssignExpr) *itemDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i itemDo) Assign(attrs ...field.AssignExpr) *itemDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i itemDo) Joins(fields ...field.RelationField) *itemDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i itemDo) Preload(fields ...field.RelationField) *itemDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i itemDo) FirstOrInit() (*model.Item, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) FirstOrCreate() (*model.Item, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Item), nil
	}
}

func (i itemDo) FindByPage(offset int, limit int) (result []*model.Item, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i itemDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i itemDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i itemDo) Delete(models ...*model.Item) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *itemDo) withDO(do gen.Dao) *itemDo {
	i.DO = *do.(*gen.DO)
	return i
}
