// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newItemNote(db *gorm.DB, opts ...gen.DOOption) itemNote {
	_itemNote := itemNote{}

	_itemNote.itemNoteDo.UseDB(db, opts...)
	_itemNote.itemNoteDo.UseModel(&model.ItemNote{})

	tableName := _itemNote.itemNoteDo.TableName()
	_itemNote.ALL = field.NewAsterisk(tableName)
	_itemNote.ItemID = field.NewInt32(tableName, "itemID")
	_itemNote.ParentItemID = field.NewInt32(tableName, "parentItemID")
	_itemNote.Note = field.NewString(tableName, "note")
	_itemNote.Title = field.NewString(tableName, "title")

	_itemNote.fillFieldMap()

	return _itemNote
}

type itemNote struct {
	itemNoteDo itemNoteDo

	ALL          field.Asterisk
	ItemID       field.Int32
	ParentItemID field.Int32
	Note         field.String
	Title        field.String

	fieldMap map[string]field.Expr
}

func (i itemNote) Table(newTableName string) *itemNote {
	i.itemNoteDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i itemNote) As(alias string) *itemNote {
	i.itemNoteDo.DO = *(i.itemNoteDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *itemNote) updateTableName(table string) *itemNote {
	i.ALL = field.NewAsterisk(table)
	i.ItemID = field.NewInt32(table, "itemID")
	i.ParentItemID = field.NewInt32(table, "parentItemID")
	i.Note = field.NewString(table, "note")
	i.Title = field.NewString(table, "title")

	i.fillFieldMap()

	return i
}

func (i *itemNote) WithContext(ctx context.Context) *itemNoteDo { return i.itemNoteDo.WithContext(ctx) }

func (i itemNote) TableName() string { return i.itemNoteDo.TableName() }

func (i itemNote) Alias() string { return i.itemNoteDo.Alias() }

func (i itemNote) Columns(cols ...field.Expr) gen.Columns { return i.itemNoteDo.Columns(cols...) }

func (i *itemNote) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *itemNote) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 4)
	i.fieldMap["itemID"] = i.ItemID
	i.fieldMap["parentItemID"] = i.ParentItemID
	i.fieldMap["note"] = i.Note
	i.fieldMap["title"] = i.Title
}

func (i itemNote) clone(db *gorm.DB) itemNote {
	i.itemNoteDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i itemNote) replaceDB(db *gorm.DB) itemNote {
	i.itemNoteDo.ReplaceDB(db)
	return i
}

type itemNoteDo struct{ gen.DO }

func (i itemNoteDo) Debug() *itemNoteDo {
	return i.withDO(i.DO.Debug())
}

func (i itemNoteDo) WithContext(ctx context.Context) *itemNoteDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i itemNoteDo) ReadDB() *itemNoteDo {
	return i.Clauses(dbresolver.Read)
}

func (i itemNoteDo) WriteDB() *itemNoteDo {
	return i.Clauses(dbresolver.Write)
}

func (i itemNoteDo) Session(config *gorm.Session) *itemNoteDo {
	return i.withDO(i.DO.Session(config))
}

func (i itemNoteDo) Clauses(conds ...clause.Expression) *itemNoteDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i itemNoteDo) Returning(value interface{}, columns ...string) *itemNoteDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i itemNoteDo) Not(conds ...gen.Condition) *itemNoteDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i itemNoteDo) Or(conds ...gen.Condition) *itemNoteDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i itemNoteDo) Select(conds ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i itemNoteDo) Where(conds ...gen.Condition) *itemNoteDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i itemNoteDo) Order(conds ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i itemNoteDo) Distinct(cols ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i itemNoteDo) Omit(cols ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i itemNoteDo) Join(table schema.Tabler, on ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i itemNoteDo) LeftJoin(table schema.Tabler, on ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i itemNoteDo) RightJoin(table schema.Tabler, on ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i itemNoteDo) Group(cols ...field.Expr) *itemNoteDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i itemNoteDo) Having(conds ...gen.Condition) *itemNoteDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i itemNoteDo) Limit(limit int) *itemNoteDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i itemNoteDo) Offset(offset int) *itemNoteDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i itemNoteDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *itemNoteDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i itemNoteDo) Unscoped() *itemNoteDo {
	return i.withDO(i.DO.Unscoped())
}

func (i itemNoteDo) Create(values ...*model.ItemNote) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i itemNoteDo) CreateInBatches(values []*model.ItemNote, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i itemNoteDo) Save(values ...*model.ItemNote) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i itemNoteDo) First() (*model.ItemNote, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemNote), nil
	}
}

func (i itemNoteDo) Take() (*model.ItemNote, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemNote), nil
	}
}

func (i itemNoteDo) Last() (*model.ItemNote, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemNote), nil
	}
}

func (i itemNoteDo) Find() ([]*model.ItemNote, error) {
	result, err := i.DO.Find()
	return result.([]*model.ItemNote), err
}

func (i itemNoteDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ItemNote, err error) {
	buf := make([]*model.ItemNote, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i itemNoteDo) FindInBatches(result *[]*model.ItemNote, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i itemNoteDo) Attrs(attrs ...field.AssignExpr) *itemNoteDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i itemNoteDo) Assign(attrs ...field.AssignExpr) *itemNoteDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i itemNoteDo) Joins(fields ...field.RelationField) *itemNoteDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i itemNoteDo) Preload(fields ...field.RelationField) *itemNoteDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i itemNoteDo) FirstOrInit() (*model.ItemNote, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemNote), nil
	}
}

func (i itemNoteDo) FirstOrCreate() (*model.ItemNote, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemNote), nil
	}
}

func (i itemNoteDo) FindByPage(offset int, limit int) (result []*model.ItemNote, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i itemNoteDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i itemNoteDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i itemNoteDo) Delete(models ...*model.ItemNote) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *itemNoteDo) withDO(do gen.Dao) *itemNoteDo {
	i.DO = *do.(*gen.DO)
	return i
}
