// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newItemDataValue(db *gorm.DB, opts ...gen.DOOption) itemDataValue {
	_itemDataValue := itemDataValue{}

	_itemDataValue.itemDataValueDo.UseDB(db, opts...)
	_itemDataValue.itemDataValueDo.UseModel(&model.ItemDataValue{})

	tableName := _itemDataValue.itemDataValueDo.TableName()
	_itemDataValue.ALL = field.NewAsterisk(tableName)
	_itemDataValue.ValueID = field.NewInt32(tableName, "valueID")
	_itemDataValue.Value = field.NewString(tableName, "value")

	_itemDataValue.fillFieldMap()

	return _itemDataValue
}

type itemDataValue struct {
	itemDataValueDo itemDataValueDo

	ALL     field.Asterisk
	ValueID field.Int32
	Value   field.String

	fieldMap map[string]field.Expr
}

func (i itemDataValue) Table(newTableName string) *itemDataValue {
	i.itemDataValueDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i itemDataValue) As(alias string) *itemDataValue {
	i.itemDataValueDo.DO = *(i.itemDataValueDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *itemDataValue) updateTableName(table string) *itemDataValue {
	i.ALL = field.NewAsterisk(table)
	i.ValueID = field.NewInt32(table, "valueID")
	i.Value = field.NewString(table, "value")

	i.fillFieldMap()

	return i
}

func (i *itemDataValue) WithContext(ctx context.Context) *itemDataValueDo {
	return i.itemDataValueDo.WithContext(ctx)
}

func (i itemDataValue) TableName() string { return i.itemDataValueDo.TableName() }

func (i itemDataValue) Alias() string { return i.itemDataValueDo.Alias() }

func (i itemDataValue) Columns(cols ...field.Expr) gen.Columns {
	return i.itemDataValueDo.Columns(cols...)
}

func (i *itemDataValue) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *itemDataValue) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 2)
	i.fieldMap["valueID"] = i.ValueID
	i.fieldMap["value"] = i.Value
}

func (i itemDataValue) clone(db *gorm.DB) itemDataValue {
	i.itemDataValueDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i itemDataValue) replaceDB(db *gorm.DB) itemDataValue {
	i.itemDataValueDo.ReplaceDB(db)
	return i
}

type itemDataValueDo struct{ gen.DO }

func (i itemDataValueDo) Debug() *itemDataValueDo {
	return i.withDO(i.DO.Debug())
}

func (i itemDataValueDo) WithContext(ctx context.Context) *itemDataValueDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i itemDataValueDo) ReadDB() *itemDataValueDo {
	return i.Clauses(dbresolver.Read)
}

func (i itemDataValueDo) WriteDB() *itemDataValueDo {
	return i.Clauses(dbresolver.Write)
}

func (i itemDataValueDo) Session(config *gorm.Session) *itemDataValueDo {
	return i.withDO(i.DO.Session(config))
}

func (i itemDataValueDo) Clauses(conds ...clause.Expression) *itemDataValueDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i itemDataValueDo) Returning(value interface{}, columns ...string) *itemDataValueDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i itemDataValueDo) Not(conds ...gen.Condition) *itemDataValueDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i itemDataValueDo) Or(conds ...gen.Condition) *itemDataValueDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i itemDataValueDo) Select(conds ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i itemDataValueDo) Where(conds ...gen.Condition) *itemDataValueDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i itemDataValueDo) Order(conds ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i itemDataValueDo) Distinct(cols ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i itemDataValueDo) Omit(cols ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i itemDataValueDo) Join(table schema.Tabler, on ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i itemDataValueDo) LeftJoin(table schema.Tabler, on ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i itemDataValueDo) RightJoin(table schema.Tabler, on ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i itemDataValueDo) Group(cols ...field.Expr) *itemDataValueDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i itemDataValueDo) Having(conds ...gen.Condition) *itemDataValueDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i itemDataValueDo) Limit(limit int) *itemDataValueDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i itemDataValueDo) Offset(offset int) *itemDataValueDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i itemDataValueDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *itemDataValueDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i itemDataValueDo) Unscoped() *itemDataValueDo {
	return i.withDO(i.DO.Unscoped())
}

func (i itemDataValueDo) Create(values ...*model.ItemDataValue) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i itemDataValueDo) CreateInBatches(values []*model.ItemDataValue, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i itemDataValueDo) Save(values ...*model.ItemDataValue) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i itemDataValueDo) First() (*model.ItemDataValue, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemDataValue), nil
	}
}

func (i itemDataValueDo) Take() (*model.ItemDataValue, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemDataValue), nil
	}
}

func (i itemDataValueDo) Last() (*model.ItemDataValue, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemDataValue), nil
	}
}

func (i itemDataValueDo) Find() ([]*model.ItemDataValue, error) {
	result, err := i.DO.Find()
	return result.([]*model.ItemDataValue), err
}

func (i itemDataValueDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ItemDataValue, err error) {
	buf := make([]*model.ItemDataValue, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i itemDataValueDo) FindInBatches(result *[]*model.ItemDataValue, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i itemDataValueDo) Attrs(attrs ...field.AssignExpr) *itemDataValueDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i itemDataValueDo) Assign(attrs ...field.AssignExpr) *itemDataValueDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i itemDataValueDo) Joins(fields ...field.RelationField) *itemDataValueDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i itemDataValueDo) Preload(fields ...field.RelationField) *itemDataValueDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i itemDataValueDo) FirstOrInit() (*model.ItemDataValue, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemDataValue), nil
	}
}

func (i itemDataValueDo) FirstOrCreate() (*model.ItemDataValue, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ItemDataValue), nil
	}
}

func (i itemDataValueDo) FindByPage(offset int, limit int) (result []*model.ItemDataValue, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i itemDataValueDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i itemDataValueDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i itemDataValueDo) Delete(models ...*model.ItemDataValue) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *itemDataValueDo) withDO(do gen.Dao) *itemDataValueDo {
	i.DO = *do.(*gen.DO)
	return i
}
