// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newProxy(db *gorm.DB, opts ...gen.DOOption) proxy {
	_proxy := proxy{}

	_proxy.proxyDo.UseDB(db, opts...)
	_proxy.proxyDo.UseModel(&model.Proxy{})

	tableName := _proxy.proxyDo.TableName()
	_proxy.ALL = field.NewAsterisk(tableName)
	_proxy.ProxyID = field.NewInt32(tableName, "proxyID")
	_proxy.MultiHost = field.NewInt32(tableName, "multiHost")
	_proxy.AutoAssociate = field.NewInt32(tableName, "autoAssociate")
	_proxy.Scheme = field.NewString(tableName, "scheme")

	_proxy.fillFieldMap()

	return _proxy
}

type proxy struct {
	proxyDo proxyDo

	ALL           field.Asterisk
	ProxyID       field.Int32
	MultiHost     field.Int32
	AutoAssociate field.Int32
	Scheme        field.String

	fieldMap map[string]field.Expr
}

func (p proxy) Table(newTableName string) *proxy {
	p.proxyDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p proxy) As(alias string) *proxy {
	p.proxyDo.DO = *(p.proxyDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *proxy) updateTableName(table string) *proxy {
	p.ALL = field.NewAsterisk(table)
	p.ProxyID = field.NewInt32(table, "proxyID")
	p.MultiHost = field.NewInt32(table, "multiHost")
	p.AutoAssociate = field.NewInt32(table, "autoAssociate")
	p.Scheme = field.NewString(table, "scheme")

	p.fillFieldMap()

	return p
}

func (p *proxy) WithContext(ctx context.Context) *proxyDo { return p.proxyDo.WithContext(ctx) }

func (p proxy) TableName() string { return p.proxyDo.TableName() }

func (p proxy) Alias() string { return p.proxyDo.Alias() }

func (p proxy) Columns(cols ...field.Expr) gen.Columns { return p.proxyDo.Columns(cols...) }

func (p *proxy) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *proxy) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 4)
	p.fieldMap["proxyID"] = p.ProxyID
	p.fieldMap["multiHost"] = p.MultiHost
	p.fieldMap["autoAssociate"] = p.AutoAssociate
	p.fieldMap["scheme"] = p.Scheme
}

func (p proxy) clone(db *gorm.DB) proxy {
	p.proxyDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p proxy) replaceDB(db *gorm.DB) proxy {
	p.proxyDo.ReplaceDB(db)
	return p
}

type proxyDo struct{ gen.DO }

func (p proxyDo) Debug() *proxyDo {
	return p.withDO(p.DO.Debug())
}

func (p proxyDo) WithContext(ctx context.Context) *proxyDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p proxyDo) ReadDB() *proxyDo {
	return p.Clauses(dbresolver.Read)
}

func (p proxyDo) WriteDB() *proxyDo {
	return p.Clauses(dbresolver.Write)
}

func (p proxyDo) Session(config *gorm.Session) *proxyDo {
	return p.withDO(p.DO.Session(config))
}

func (p proxyDo) Clauses(conds ...clause.Expression) *proxyDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p proxyDo) Returning(value interface{}, columns ...string) *proxyDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p proxyDo) Not(conds ...gen.Condition) *proxyDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p proxyDo) Or(conds ...gen.Condition) *proxyDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p proxyDo) Select(conds ...field.Expr) *proxyDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p proxyDo) Where(conds ...gen.Condition) *proxyDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p proxyDo) Order(conds ...field.Expr) *proxyDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p proxyDo) Distinct(cols ...field.Expr) *proxyDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p proxyDo) Omit(cols ...field.Expr) *proxyDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p proxyDo) Join(table schema.Tabler, on ...field.Expr) *proxyDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p proxyDo) LeftJoin(table schema.Tabler, on ...field.Expr) *proxyDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p proxyDo) RightJoin(table schema.Tabler, on ...field.Expr) *proxyDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p proxyDo) Group(cols ...field.Expr) *proxyDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p proxyDo) Having(conds ...gen.Condition) *proxyDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p proxyDo) Limit(limit int) *proxyDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p proxyDo) Offset(offset int) *proxyDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p proxyDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *proxyDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p proxyDo) Unscoped() *proxyDo {
	return p.withDO(p.DO.Unscoped())
}

func (p proxyDo) Create(values ...*model.Proxy) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p proxyDo) CreateInBatches(values []*model.Proxy, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p proxyDo) Save(values ...*model.Proxy) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p proxyDo) First() (*model.Proxy, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Proxy), nil
	}
}

func (p proxyDo) Take() (*model.Proxy, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Proxy), nil
	}
}

func (p proxyDo) Last() (*model.Proxy, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Proxy), nil
	}
}

func (p proxyDo) Find() ([]*model.Proxy, error) {
	result, err := p.DO.Find()
	return result.([]*model.Proxy), err
}

func (p proxyDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Proxy, err error) {
	buf := make([]*model.Proxy, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p proxyDo) FindInBatches(result *[]*model.Proxy, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p proxyDo) Attrs(attrs ...field.AssignExpr) *proxyDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p proxyDo) Assign(attrs ...field.AssignExpr) *proxyDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p proxyDo) Joins(fields ...field.RelationField) *proxyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p proxyDo) Preload(fields ...field.RelationField) *proxyDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p proxyDo) FirstOrInit() (*model.Proxy, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Proxy), nil
	}
}

func (p proxyDo) FirstOrCreate() (*model.Proxy, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Proxy), nil
	}
}

func (p proxyDo) FindByPage(offset int, limit int) (result []*model.Proxy, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p proxyDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p proxyDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p proxyDo) Delete(models ...*model.Proxy) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *proxyDo) withDO(do gen.Dao) *proxyDo {
	p.DO = *do.(*gen.DO)
	return p
}
