// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newProxyHost(db *gorm.DB, opts ...gen.DOOption) proxyHost {
	_proxyHost := proxyHost{}

	_proxyHost.proxyHostDo.UseDB(db, opts...)
	_proxyHost.proxyHostDo.UseModel(&model.ProxyHost{})

	tableName := _proxyHost.proxyHostDo.TableName()
	_proxyHost.ALL = field.NewAsterisk(tableName)
	_proxyHost.HostID = field.NewInt32(tableName, "hostID")
	_proxyHost.ProxyID = field.NewInt32(tableName, "proxyID")
	_proxyHost.Hostname = field.NewString(tableName, "hostname")

	_proxyHost.fillFieldMap()

	return _proxyHost
}

type proxyHost struct {
	proxyHostDo proxyHostDo

	ALL      field.Asterisk
	HostID   field.Int32
	ProxyID  field.Int32
	Hostname field.String

	fieldMap map[string]field.Expr
}

func (p proxyHost) Table(newTableName string) *proxyHost {
	p.proxyHostDo.UseTable(newTableName)
	return p.updateTableName(newTableName)
}

func (p proxyHost) As(alias string) *proxyHost {
	p.proxyHostDo.DO = *(p.proxyHostDo.As(alias).(*gen.DO))
	return p.updateTableName(alias)
}

func (p *proxyHost) updateTableName(table string) *proxyHost {
	p.ALL = field.NewAsterisk(table)
	p.HostID = field.NewInt32(table, "hostID")
	p.ProxyID = field.NewInt32(table, "proxyID")
	p.Hostname = field.NewString(table, "hostname")

	p.fillFieldMap()

	return p
}

func (p *proxyHost) WithContext(ctx context.Context) *proxyHostDo {
	return p.proxyHostDo.WithContext(ctx)
}

func (p proxyHost) TableName() string { return p.proxyHostDo.TableName() }

func (p proxyHost) Alias() string { return p.proxyHostDo.Alias() }

func (p proxyHost) Columns(cols ...field.Expr) gen.Columns { return p.proxyHostDo.Columns(cols...) }

func (p *proxyHost) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := p.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (p *proxyHost) fillFieldMap() {
	p.fieldMap = make(map[string]field.Expr, 3)
	p.fieldMap["hostID"] = p.HostID
	p.fieldMap["proxyID"] = p.ProxyID
	p.fieldMap["hostname"] = p.Hostname
}

func (p proxyHost) clone(db *gorm.DB) proxyHost {
	p.proxyHostDo.ReplaceConnPool(db.Statement.ConnPool)
	return p
}

func (p proxyHost) replaceDB(db *gorm.DB) proxyHost {
	p.proxyHostDo.ReplaceDB(db)
	return p
}

type proxyHostDo struct{ gen.DO }

func (p proxyHostDo) Debug() *proxyHostDo {
	return p.withDO(p.DO.Debug())
}

func (p proxyHostDo) WithContext(ctx context.Context) *proxyHostDo {
	return p.withDO(p.DO.WithContext(ctx))
}

func (p proxyHostDo) ReadDB() *proxyHostDo {
	return p.Clauses(dbresolver.Read)
}

func (p proxyHostDo) WriteDB() *proxyHostDo {
	return p.Clauses(dbresolver.Write)
}

func (p proxyHostDo) Session(config *gorm.Session) *proxyHostDo {
	return p.withDO(p.DO.Session(config))
}

func (p proxyHostDo) Clauses(conds ...clause.Expression) *proxyHostDo {
	return p.withDO(p.DO.Clauses(conds...))
}

func (p proxyHostDo) Returning(value interface{}, columns ...string) *proxyHostDo {
	return p.withDO(p.DO.Returning(value, columns...))
}

func (p proxyHostDo) Not(conds ...gen.Condition) *proxyHostDo {
	return p.withDO(p.DO.Not(conds...))
}

func (p proxyHostDo) Or(conds ...gen.Condition) *proxyHostDo {
	return p.withDO(p.DO.Or(conds...))
}

func (p proxyHostDo) Select(conds ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.Select(conds...))
}

func (p proxyHostDo) Where(conds ...gen.Condition) *proxyHostDo {
	return p.withDO(p.DO.Where(conds...))
}

func (p proxyHostDo) Order(conds ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.Order(conds...))
}

func (p proxyHostDo) Distinct(cols ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.Distinct(cols...))
}

func (p proxyHostDo) Omit(cols ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.Omit(cols...))
}

func (p proxyHostDo) Join(table schema.Tabler, on ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.Join(table, on...))
}

func (p proxyHostDo) LeftJoin(table schema.Tabler, on ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.LeftJoin(table, on...))
}

func (p proxyHostDo) RightJoin(table schema.Tabler, on ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.RightJoin(table, on...))
}

func (p proxyHostDo) Group(cols ...field.Expr) *proxyHostDo {
	return p.withDO(p.DO.Group(cols...))
}

func (p proxyHostDo) Having(conds ...gen.Condition) *proxyHostDo {
	return p.withDO(p.DO.Having(conds...))
}

func (p proxyHostDo) Limit(limit int) *proxyHostDo {
	return p.withDO(p.DO.Limit(limit))
}

func (p proxyHostDo) Offset(offset int) *proxyHostDo {
	return p.withDO(p.DO.Offset(offset))
}

func (p proxyHostDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *proxyHostDo {
	return p.withDO(p.DO.Scopes(funcs...))
}

func (p proxyHostDo) Unscoped() *proxyHostDo {
	return p.withDO(p.DO.Unscoped())
}

func (p proxyHostDo) Create(values ...*model.ProxyHost) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Create(values)
}

func (p proxyHostDo) CreateInBatches(values []*model.ProxyHost, batchSize int) error {
	return p.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (p proxyHostDo) Save(values ...*model.ProxyHost) error {
	if len(values) == 0 {
		return nil
	}
	return p.DO.Save(values)
}

func (p proxyHostDo) First() (*model.ProxyHost, error) {
	if result, err := p.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProxyHost), nil
	}
}

func (p proxyHostDo) Take() (*model.ProxyHost, error) {
	if result, err := p.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProxyHost), nil
	}
}

func (p proxyHostDo) Last() (*model.ProxyHost, error) {
	if result, err := p.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProxyHost), nil
	}
}

func (p proxyHostDo) Find() ([]*model.ProxyHost, error) {
	result, err := p.DO.Find()
	return result.([]*model.ProxyHost), err
}

func (p proxyHostDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.ProxyHost, err error) {
	buf := make([]*model.ProxyHost, 0, batchSize)
	err = p.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (p proxyHostDo) FindInBatches(result *[]*model.ProxyHost, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return p.DO.FindInBatches(result, batchSize, fc)
}

func (p proxyHostDo) Attrs(attrs ...field.AssignExpr) *proxyHostDo {
	return p.withDO(p.DO.Attrs(attrs...))
}

func (p proxyHostDo) Assign(attrs ...field.AssignExpr) *proxyHostDo {
	return p.withDO(p.DO.Assign(attrs...))
}

func (p proxyHostDo) Joins(fields ...field.RelationField) *proxyHostDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Joins(_f))
	}
	return &p
}

func (p proxyHostDo) Preload(fields ...field.RelationField) *proxyHostDo {
	for _, _f := range fields {
		p = *p.withDO(p.DO.Preload(_f))
	}
	return &p
}

func (p proxyHostDo) FirstOrInit() (*model.ProxyHost, error) {
	if result, err := p.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProxyHost), nil
	}
}

func (p proxyHostDo) FirstOrCreate() (*model.ProxyHost, error) {
	if result, err := p.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.ProxyHost), nil
	}
}

func (p proxyHostDo) FindByPage(offset int, limit int) (result []*model.ProxyHost, count int64, err error) {
	result, err = p.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = p.Offset(-1).Limit(-1).Count()
	return
}

func (p proxyHostDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = p.Count()
	if err != nil {
		return
	}

	err = p.Offset(offset).Limit(limit).Scan(result)
	return
}

func (p proxyHostDo) Scan(result interface{}) (err error) {
	return p.DO.Scan(result)
}

func (p proxyHostDo) Delete(models ...*model.ProxyHost) (result gen.ResultInfo, err error) {
	return p.DO.Delete(models)
}

func (p *proxyHostDo) withDO(do gen.Dao) *proxyHostDo {
	p.DO = *do.(*gen.DO)
	return p
}
