// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"bibliana/dao/model"
)

func newSyncObjectType(db *gorm.DB, opts ...gen.DOOption) syncObjectType {
	_syncObjectType := syncObjectType{}

	_syncObjectType.syncObjectTypeDo.UseDB(db, opts...)
	_syncObjectType.syncObjectTypeDo.UseModel(&model.SyncObjectType{})

	tableName := _syncObjectType.syncObjectTypeDo.TableName()
	_syncObjectType.ALL = field.NewAsterisk(tableName)
	_syncObjectType.SyncObjectTypeID = field.NewInt32(tableName, "syncObjectTypeID")
	_syncObjectType.Name = field.NewString(tableName, "name")

	_syncObjectType.fillFieldMap()

	return _syncObjectType
}

type syncObjectType struct {
	syncObjectTypeDo syncObjectTypeDo

	ALL              field.Asterisk
	SyncObjectTypeID field.Int32
	Name             field.String

	fieldMap map[string]field.Expr
}

func (s syncObjectType) Table(newTableName string) *syncObjectType {
	s.syncObjectTypeDo.UseTable(newTableName)
	return s.updateTableName(newTableName)
}

func (s syncObjectType) As(alias string) *syncObjectType {
	s.syncObjectTypeDo.DO = *(s.syncObjectTypeDo.As(alias).(*gen.DO))
	return s.updateTableName(alias)
}

func (s *syncObjectType) updateTableName(table string) *syncObjectType {
	s.ALL = field.NewAsterisk(table)
	s.SyncObjectTypeID = field.NewInt32(table, "syncObjectTypeID")
	s.Name = field.NewString(table, "name")

	s.fillFieldMap()

	return s
}

func (s *syncObjectType) WithContext(ctx context.Context) *syncObjectTypeDo {
	return s.syncObjectTypeDo.WithContext(ctx)
}

func (s syncObjectType) TableName() string { return s.syncObjectTypeDo.TableName() }

func (s syncObjectType) Alias() string { return s.syncObjectTypeDo.Alias() }

func (s syncObjectType) Columns(cols ...field.Expr) gen.Columns {
	return s.syncObjectTypeDo.Columns(cols...)
}

func (s *syncObjectType) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := s.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (s *syncObjectType) fillFieldMap() {
	s.fieldMap = make(map[string]field.Expr, 2)
	s.fieldMap["syncObjectTypeID"] = s.SyncObjectTypeID
	s.fieldMap["name"] = s.Name
}

func (s syncObjectType) clone(db *gorm.DB) syncObjectType {
	s.syncObjectTypeDo.ReplaceConnPool(db.Statement.ConnPool)
	return s
}

func (s syncObjectType) replaceDB(db *gorm.DB) syncObjectType {
	s.syncObjectTypeDo.ReplaceDB(db)
	return s
}

type syncObjectTypeDo struct{ gen.DO }

func (s syncObjectTypeDo) Debug() *syncObjectTypeDo {
	return s.withDO(s.DO.Debug())
}

func (s syncObjectTypeDo) WithContext(ctx context.Context) *syncObjectTypeDo {
	return s.withDO(s.DO.WithContext(ctx))
}

func (s syncObjectTypeDo) ReadDB() *syncObjectTypeDo {
	return s.Clauses(dbresolver.Read)
}

func (s syncObjectTypeDo) WriteDB() *syncObjectTypeDo {
	return s.Clauses(dbresolver.Write)
}

func (s syncObjectTypeDo) Session(config *gorm.Session) *syncObjectTypeDo {
	return s.withDO(s.DO.Session(config))
}

func (s syncObjectTypeDo) Clauses(conds ...clause.Expression) *syncObjectTypeDo {
	return s.withDO(s.DO.Clauses(conds...))
}

func (s syncObjectTypeDo) Returning(value interface{}, columns ...string) *syncObjectTypeDo {
	return s.withDO(s.DO.Returning(value, columns...))
}

func (s syncObjectTypeDo) Not(conds ...gen.Condition) *syncObjectTypeDo {
	return s.withDO(s.DO.Not(conds...))
}

func (s syncObjectTypeDo) Or(conds ...gen.Condition) *syncObjectTypeDo {
	return s.withDO(s.DO.Or(conds...))
}

func (s syncObjectTypeDo) Select(conds ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.Select(conds...))
}

func (s syncObjectTypeDo) Where(conds ...gen.Condition) *syncObjectTypeDo {
	return s.withDO(s.DO.Where(conds...))
}

func (s syncObjectTypeDo) Order(conds ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.Order(conds...))
}

func (s syncObjectTypeDo) Distinct(cols ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.Distinct(cols...))
}

func (s syncObjectTypeDo) Omit(cols ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.Omit(cols...))
}

func (s syncObjectTypeDo) Join(table schema.Tabler, on ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.Join(table, on...))
}

func (s syncObjectTypeDo) LeftJoin(table schema.Tabler, on ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.LeftJoin(table, on...))
}

func (s syncObjectTypeDo) RightJoin(table schema.Tabler, on ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.RightJoin(table, on...))
}

func (s syncObjectTypeDo) Group(cols ...field.Expr) *syncObjectTypeDo {
	return s.withDO(s.DO.Group(cols...))
}

func (s syncObjectTypeDo) Having(conds ...gen.Condition) *syncObjectTypeDo {
	return s.withDO(s.DO.Having(conds...))
}

func (s syncObjectTypeDo) Limit(limit int) *syncObjectTypeDo {
	return s.withDO(s.DO.Limit(limit))
}

func (s syncObjectTypeDo) Offset(offset int) *syncObjectTypeDo {
	return s.withDO(s.DO.Offset(offset))
}

func (s syncObjectTypeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *syncObjectTypeDo {
	return s.withDO(s.DO.Scopes(funcs...))
}

func (s syncObjectTypeDo) Unscoped() *syncObjectTypeDo {
	return s.withDO(s.DO.Unscoped())
}

func (s syncObjectTypeDo) Create(values ...*model.SyncObjectType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Create(values)
}

func (s syncObjectTypeDo) CreateInBatches(values []*model.SyncObjectType, batchSize int) error {
	return s.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (s syncObjectTypeDo) Save(values ...*model.SyncObjectType) error {
	if len(values) == 0 {
		return nil
	}
	return s.DO.Save(values)
}

func (s syncObjectTypeDo) First() (*model.SyncObjectType, error) {
	if result, err := s.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncObjectType), nil
	}
}

func (s syncObjectTypeDo) Take() (*model.SyncObjectType, error) {
	if result, err := s.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncObjectType), nil
	}
}

func (s syncObjectTypeDo) Last() (*model.SyncObjectType, error) {
	if result, err := s.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncObjectType), nil
	}
}

func (s syncObjectTypeDo) Find() ([]*model.SyncObjectType, error) {
	result, err := s.DO.Find()
	return result.([]*model.SyncObjectType), err
}

func (s syncObjectTypeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.SyncObjectType, err error) {
	buf := make([]*model.SyncObjectType, 0, batchSize)
	err = s.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (s syncObjectTypeDo) FindInBatches(result *[]*model.SyncObjectType, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return s.DO.FindInBatches(result, batchSize, fc)
}

func (s syncObjectTypeDo) Attrs(attrs ...field.AssignExpr) *syncObjectTypeDo {
	return s.withDO(s.DO.Attrs(attrs...))
}

func (s syncObjectTypeDo) Assign(attrs ...field.AssignExpr) *syncObjectTypeDo {
	return s.withDO(s.DO.Assign(attrs...))
}

func (s syncObjectTypeDo) Joins(fields ...field.RelationField) *syncObjectTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Joins(_f))
	}
	return &s
}

func (s syncObjectTypeDo) Preload(fields ...field.RelationField) *syncObjectTypeDo {
	for _, _f := range fields {
		s = *s.withDO(s.DO.Preload(_f))
	}
	return &s
}

func (s syncObjectTypeDo) FirstOrInit() (*model.SyncObjectType, error) {
	if result, err := s.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncObjectType), nil
	}
}

func (s syncObjectTypeDo) FirstOrCreate() (*model.SyncObjectType, error) {
	if result, err := s.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.SyncObjectType), nil
	}
}

func (s syncObjectTypeDo) FindByPage(offset int, limit int) (result []*model.SyncObjectType, count int64, err error) {
	result, err = s.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = s.Offset(-1).Limit(-1).Count()
	return
}

func (s syncObjectTypeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = s.Count()
	if err != nil {
		return
	}

	err = s.Offset(offset).Limit(limit).Scan(result)
	return
}

func (s syncObjectTypeDo) Scan(result interface{}) (err error) {
	return s.DO.Scan(result)
}

func (s syncObjectTypeDo) Delete(models ...*model.SyncObjectType) (result gen.ResultInfo, err error) {
	return s.DO.Delete(models)
}

func (s *syncObjectTypeDo) withDO(do gen.Dao) *syncObjectTypeDo {
	s.DO = *do.(*gen.DO)
	return s
}
