// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAttribute = "attributes"

// Attribute mapped from table <attributes>
type Attribute struct {
	FieldID       *int32  `gorm:"column:fieldID;type:INTEGER" json:"fieldID"`
	FieldName     *string `gorm:"column:fieldName;type:TEXT" json:"fieldName"`
	FieldFormatID *int32  `gorm:"column:fieldFormatID;type:INT" json:"fieldFormatID"`
}

// TableName Attribute's table name
func (*Attribute) TableName() string {
	return TableNameAttribute
}
