// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameBaseFieldMappingsCombined = "baseFieldMappingsCombined"

// BaseFieldMappingsCombined mapped from table <baseFieldMappingsCombined>
type BaseFieldMappingsCombined struct {
	ItemTypeID  *int32 `gorm:"column:itemTypeID;type:INT;primaryKey" json:"itemTypeID"`
	BaseFieldID *int32 `gorm:"column:baseFieldID;type:INT;index:baseFieldMappingsCombined_baseFieldID,priority:1" json:"baseFieldID"`
	FieldID     *int32 `gorm:"column:fieldID;type:INT;index:baseFieldMappingsCombined_fieldID,priority:1" json:"fieldID"`
}

// TableName BaseFieldMappingsCombined's table name
func (*BaseFieldMappingsCombined) TableName() string {
	return TableNameBaseFieldMappingsCombined
}
