// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameCollection = "collections"

// Collection mapped from table <collections>
type Collection struct {
	CollectionID       *int32    `gorm:"column:collectionID;type:INTEGER;primaryKey" json:"collectionID"`
	CollectionName     string    `gorm:"column:collectionName;type:TEXT;not null" json:"collectionName"`
	ParentCollectionID *int32    `gorm:"column:parentCollectionID;type:INT" json:"parentCollectionID"`
	ClientDateModified time.Time `gorm:"column:clientDateModified;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"clientDateModified"`
	LibraryID          int32     `gorm:"column:libraryID;type:INT;not null" json:"libraryID"`
	Key                string    `gorm:"column:key;type:TEXT;not null" json:"key"`
	Version            int32     `gorm:"column:version;type:INT;not null" json:"version"`
	Synced             int32     `gorm:"column:synced;type:INT;not null;index:collections_synced,priority:1" json:"synced"`
}

// TableName Collection's table name
func (*Collection) TableName() string {
	return TableNameCollection
}
