// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCreator = "creators"

// Creator mapped from table <creators>
type Creator struct {
	CreatorID *int32  `gorm:"column:creatorID;type:INTEGER;primaryKey" json:"creatorID"`
	FirstName *string `gorm:"column:firstName;type:TEXT" json:"firstName"`
	LastName  *string `gorm:"column:lastName;type:TEXT" json:"lastName"`
	FieldMode *int32  `gorm:"column:fieldMode;type:INT" json:"fieldMode"`
}

// TableName Creator's table name
func (*Creator) TableName() string {
	return TableNameCreator
}
