// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomItemType = "customItemTypes"

// CustomItemType mapped from table <customItemTypes>
type CustomItemType struct {
	CustomItemTypeID *int32  `gorm:"column:customItemTypeID;type:INTEGER;primaryKey" json:"customItemTypeID"`
	TypeName         *string `gorm:"column:typeName;type:TEXT" json:"typeName"`
	Label            *string `gorm:"column:label;type:TEXT" json:"label"`
	Display          *int32  `gorm:"column:display;type:INT;default:1" json:"display"`
	Icon             *string `gorm:"column:icon;type:TEXT" json:"icon"`
}

// TableName CustomItemType's table name
func (*CustomItemType) TableName() string {
	return TableNameCustomItemType
}
