// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomItemTypeField = "customItemTypeFields"

// CustomItemTypeField mapped from table <customItemTypeFields>
type CustomItemTypeField struct {
	CustomItemTypeID int32  `gorm:"column:customItemTypeID;type:INT;primaryKey" json:"customItemTypeID"`
	FieldID          *int32 `gorm:"column:fieldID;type:INT;index:customItemTypeFields_fieldID,priority:1" json:"fieldID"`
	CustomFieldID    *int32 `gorm:"column:customFieldID;type:INT;index:customItemTypeFields_customFieldID,priority:1" json:"customFieldID"`
	Hide             int32  `gorm:"column:hide;type:INT;not null" json:"hide"`
	OrderIndex       int32  `gorm:"column:orderIndex;type:INT;not null" json:"orderIndex"`
}

// TableName CustomItemTypeField's table name
func (*CustomItemTypeField) TableName() string {
	return TableNameCustomItemTypeField
}
