// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCustomBaseFieldMapping = "customBaseFieldMappings"

// CustomBaseFieldMapping mapped from table <customBaseFieldMappings>
type CustomBaseFieldMapping struct {
	CustomItemTypeID *int32 `gorm:"column:customItemTypeID;type:INT;primaryKey" json:"customItemTypeID"`
	BaseFieldID      *int32 `gorm:"column:baseFieldID;type:INT;index:customBaseFieldMappings_baseFieldID,priority:1" json:"baseFieldID"`
	CustomFieldID    *int32 `gorm:"column:customFieldID;type:INT;index:customBaseFieldMappings_customFieldID,priority:1" json:"customFieldID"`
}

// TableName CustomBaseFieldMapping's table name
func (*CustomBaseFieldMapping) TableName() string {
	return TableNameCustomBaseFieldMapping
}
