// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDeletedSearch = "deletedSearches"

// DeletedSearch mapped from table <deletedSearches>
type DeletedSearch struct {
	SavedSearchID *int32 `gorm:"column:savedSearchID;type:INTEGER;primaryKey" json:"savedSearchID"`
	DateDeleted   string `gorm:"column:dateDeleted;type:DEFAULT;not null;index:deletedSearches_dateDeleted,priority:1" json:"dateDeleted"`
}

// TableName DeletedSearch's table name
func (*DeletedSearch) TableName() string {
	return TableNameDeletedSearch
}
