// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameDeletedItem = "deletedItems"

// DeletedItem mapped from table <deletedItems>
type DeletedItem struct {
	ItemID      *int32 `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	DateDeleted string `gorm:"column:dateDeleted;type:DEFAULT;not null;index:deletedItems_dateDeleted,priority:1" json:"dateDeleted"`
}

// TableName DeletedItem's table name
func (*DeletedItem) TableName() string {
	return TableNameDeletedItem
}
