// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameFeedItem = "feedItems"

// FeedItem mapped from table <feedItems>
type FeedItem struct {
	ItemID         *int32     `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	GUID           string     `gorm:"column:guid;type:TEXT;not null" json:"guid"`
	ReadTime       *time.Time `gorm:"column:readTime;type:TIMESTAMP" json:"readTime"`
	TranslatedTime *time.Time `gorm:"column:translatedTime;type:TIMESTAMP" json:"translatedTime"`
}

// TableName FeedItem's table name
func (*FeedItem) TableName() string {
	return TableNameFeedItem
}
