// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFieldFormat = "fieldFormats"

// FieldFormat mapped from table <fieldFormats>
type FieldFormat struct {
	FieldFormatID *int32  `gorm:"column:fieldFormatID;type:INTEGER;primaryKey" json:"fieldFormatID"`
	Regex         *string `gorm:"column:regex;type:TEXT" json:"regex"`
	IsInteger     *int32  `gorm:"column:isInteger;type:INT" json:"isInteger"`
}

// TableName FieldFormat's table name
func (*FieldFormat) TableName() string {
	return TableNameFieldFormat
}
