// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFileTypeMimeType = "fileTypeMimeTypes"

// FileTypeMimeType mapped from table <fileTypeMimeTypes>
type FileTypeMimeType struct {
	FileTypeID *int32  `gorm:"column:fileTypeID;type:INT;primaryKey" json:"fileTypeID"`
	MimeType   *string `gorm:"column:mimeType;type:TEXT;index:fileTypeMimeTypes_mimeType,priority:1" json:"mimeType"`
}

// TableName FileTypeMimeType's table name
func (*FileTypeMimeType) TableName() string {
	return TableNameFileTypeMimeType
}
