// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFulltextWord = "fulltextWords"

// FulltextWord mapped from table <fulltextWords>
type FulltextWord struct {
	WordID *int32  `gorm:"column:wordID;type:INTEGER;primaryKey" json:"wordID"`
	Word   *string `gorm:"column:word;type:TEXT" json:"word"`
}

// TableName FulltextWord's table name
func (*FulltextWord) TableName() string {
	return TableNameFulltextWord
}
