// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFulltextItem = "fulltextItems"

// FulltextItem mapped from table <fulltextItems>
type FulltextItem struct {
	ItemID       *int32 `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	IndexedPages *int32 `gorm:"column:indexedPages;type:INT" json:"indexedPages"`
	TotalPages   *int32 `gorm:"column:totalPages;type:INT" json:"totalPages"`
	IndexedChars *int32 `gorm:"column:indexedChars;type:INT" json:"indexedChars"`
	TotalChars   *int32 `gorm:"column:totalChars;type:INT" json:"totalChars"`
	Version      int32  `gorm:"column:version;type:INT;not null;index:fulltextItems_version,priority:1" json:"version"`
	Synced       int32  `gorm:"column:synced;type:INT;not null;index:fulltextItems_synced,priority:1" json:"synced"`
}

// TableName FulltextItem's table name
func (*FulltextItem) TableName() string {
	return TableNameFulltextItem
}
