// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameFulltextItemWord = "fulltextItemWords"

// FulltextItemWord mapped from table <fulltextItemWords>
type FulltextItemWord struct {
	WordID *int32 `gorm:"column:wordID;type:INT;primaryKey" json:"wordID"`
	ItemID *int32 `gorm:"column:itemID;type:INT;index:fulltextItemWords_itemID,priority:1" json:"itemID"`
}

// TableName FulltextItemWord's table name
func (*FulltextItemWord) TableName() string {
	return TableNameFulltextItemWord
}
