// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemAttachment = "itemAttachments"

// ItemAttachment mapped from table <itemAttachments>
type ItemAttachment struct {
	ItemID                        *int32  `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	ParentItemID                  *int32  `gorm:"column:parentItemID;type:INT;index:itemAttachments_parentItemID,priority:1" json:"parentItemID"`
	LinkMode                      *int32  `gorm:"column:linkMode;type:INT" json:"linkMode"`
	ContentType                   *string `gorm:"column:contentType;type:TEXT;index:itemAttachments_contentType,priority:1" json:"contentType"`
	CharsetID                     *int32  `gorm:"column:charsetID;type:INT;index:itemAttachments_charsetID,priority:1" json:"charsetID"`
	Path                          *string `gorm:"column:path;type:TEXT" json:"path"`
	SyncState                     *int32  `gorm:"column:syncState;type:INT;index:itemAttachments_syncState,priority:1" json:"syncState"`
	StorageModTime                *int32  `gorm:"column:storageModTime;type:INT" json:"storageModTime"`
	StorageHash                   *string `gorm:"column:storageHash;type:TEXT" json:"storageHash"`
	LastProcessedModificationTime *int32  `gorm:"column:lastProcessedModificationTime;type:INT;index:itemAttachments_lastProcessedModificationTime,priority:1" json:"lastProcessedModificationTime"`
}

// TableName ItemAttachment's table name
func (*ItemAttachment) TableName() string {
	return TableNameItemAttachment
}
