// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemDatum = "itemData"

// ItemDatum mapped from table <itemData>
type ItemDatum struct {
	ItemID  *int32  `gorm:"column:itemID;type:INT;primaryKey" json:"itemID"`
	FieldID *int32  `gorm:"column:fieldID;type:INT;index:itemData_fieldID,priority:1" json:"fieldID"`
	ValueID *string `gorm:"column:valueID;type" json:"valueID"`
}

// TableName ItemDatum's table name
func (*ItemDatum) TableName() string {
	return TableNameItemDatum
}
