// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemTypesCombined = "itemTypesCombined"

// ItemTypesCombined mapped from table <itemTypesCombined>
type ItemTypesCombined struct {
	ItemTypeID int32  `gorm:"column:itemTypeID;type:INT;primaryKey" json:"itemTypeID"`
	TypeName   string `gorm:"column:typeName;type:TEXT;not null" json:"typeName"`
	Display    int32  `gorm:"column:display;type:INT;not null;default:1; NOT NULL" json:"display"`
	Custom     int32  `gorm:"column:custom;type:INT;not null" json:"custom"`
}

// TableName ItemTypesCombined's table name
func (*ItemTypesCombined) TableName() string {
	return TableNameItemTypesCombined
}
