// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemRelation = "itemRelations"

// ItemRelation mapped from table <itemRelations>
type ItemRelation struct {
	ItemID      int32  `gorm:"column:itemID;type:INT;primaryKey" json:"itemID"`
	PredicateID int32  `gorm:"column:predicateID;type:INT;not null;index:itemRelations_predicateID,priority:1" json:"predicateID"`
	Object      string `gorm:"column:object;type:TEXT;not null;index:itemRelations_object,priority:1" json:"object"`
}

// TableName ItemRelation's table name
func (*ItemRelation) TableName() string {
	return TableNameItemRelation
}
