// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemAnnotation = "itemAnnotations"

// ItemAnnotation mapped from table <itemAnnotations>
type ItemAnnotation struct {
	ItemID       *int32  `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	ParentItemID int32   `gorm:"column:parentItemID;type:INT;not null;index:itemAnnotations_parentItemID,priority:1" json:"parentItemID"`
	Type         int32   `gorm:"column:type;type:INTEGER;not null" json:"type"`
	AuthorName   *string `gorm:"column:authorName;type:TEXT" json:"authorName"`
	Text         *string `gorm:"column:text;type:TEXT" json:"text"`
	Comment      *string `gorm:"column:comment;type:TEXT" json:"comment"`
	Color        *string `gorm:"column:color;type:TEXT" json:"color"`
	PageLabel    *string `gorm:"column:pageLabel;type:TEXT" json:"pageLabel"`
	SortIndex    string  `gorm:"column:sortIndex;type:TEXT;not null" json:"sortIndex"`
	Position     string  `gorm:"column:position;type:TEXT;not null" json:"position"`
	IsExternal   int32   `gorm:"column:isExternal;type:INT;not null" json:"isExternal"`
}

// TableName ItemAnnotation's table name
func (*ItemAnnotation) TableName() string {
	return TableNameItemAnnotation
}
