// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemNote = "itemNotes"

// ItemNote mapped from table <itemNotes>
type ItemNote struct {
	ItemID       *int32  `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	ParentItemID *int32  `gorm:"column:parentItemID;type:INT;index:itemNotes_parentItemID,priority:1" json:"parentItemID"`
	Note         *string `gorm:"column:note;type:TEXT" json:"note"`
	Title        *string `gorm:"column:title;type:TEXT" json:"title"`
}

// TableName ItemNote's table name
func (*ItemNote) TableName() string {
	return TableNameItemNote
}
