// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemTag = "itemTags"

// ItemTag mapped from table <itemTags>
type ItemTag struct {
	ItemID int32 `gorm:"column:itemID;type:INT;primaryKey" json:"itemID"`
	TagID  int32 `gorm:"column:tagID;type:INT;not null;index:itemTags_tagID,priority:1" json:"tagID"`
	Type   int32 `gorm:"column:type;type:INT;not null" json:"type"`
}

// TableName ItemTag's table name
func (*ItemTag) TableName() string {
	return TableNameItemTag
}
