// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItemTypeField = "itemTypeFields"

// ItemTypeField mapped from table <itemTypeFields>
type ItemTypeField struct {
	ItemTypeID *int32 `gorm:"column:itemTypeID;type:INT;primaryKey" json:"itemTypeID"`
	FieldID    *int32 `gorm:"column:fieldID;type:INT;index:itemTypeFields_fieldID,priority:1" json:"fieldID"`
	Hide       *int32 `gorm:"column:hide;type:INT" json:"hide"`
	OrderIndex *int32 `gorm:"column:orderIndex;type:INT" json:"orderIndex"`
}

// TableName ItemTypeField's table name
func (*ItemTypeField) TableName() string {
	return TableNameItemTypeField
}
