// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameItem = "items"

// Item mapped from table <items>
type Item struct {
	ItemID             *int32    `gorm:"column:itemID;type:INTEGER;primaryKey" json:"itemID"`
	ItemTypeID         int32     `gorm:"column:itemTypeID;type:INT;not null" json:"itemTypeID"`
	DateAdded          time.Time `gorm:"column:dateAdded;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"dateAdded"`
	DateModified       time.Time `gorm:"column:dateModified;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"dateModified"`
	ClientDateModified time.Time `gorm:"column:clientDateModified;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"clientDateModified"`
	LibraryID          int32     `gorm:"column:libraryID;type:INT;not null" json:"libraryID"`
	Key                string    `gorm:"column:key;type:TEXT;not null" json:"key"`
	Version            int32     `gorm:"column:version;type:INT;not null" json:"version"`
	Synced             int32     `gorm:"column:synced;type:INT;not null;index:items_synced,priority:1" json:"synced"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
