// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLibrary = "libraries"

// Library mapped from table <libraries>
type Library struct {
	LibraryID      *int32 `gorm:"column:libraryID;type:INTEGER;primaryKey" json:"libraryID"`
	Type           string `gorm:"column:type;type:TEXT;not null" json:"type"`
	Editable       int32  `gorm:"column:editable;type:INT;not null" json:"editable"`
	FilesEditable  int32  `gorm:"column:filesEditable;type:INT;not null" json:"filesEditable"`
	Version        int32  `gorm:"column:version;type:INT;not null" json:"version"`
	StorageVersion int32  `gorm:"column:storageVersion;type:INT;not null" json:"storageVersion"`
	LastSync       int32  `gorm:"column:lastSync;type:INT;not null" json:"lastSync"`
	Archived       int32  `gorm:"column:archived;type:INT;not null" json:"archived"`
}

// TableName Library's table name
func (*Library) TableName() string {
	return TableNameLibrary
}
