// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProxyHost = "proxyHosts"

// ProxyHost mapped from table <proxyHosts>
type ProxyHost struct {
	HostID   *int32  `gorm:"column:hostID;type:INTEGER;primaryKey" json:"hostID"`
	ProxyID  *int32  `gorm:"column:proxyID;type:INTEGER;index:proxyHosts_proxyID,priority:1" json:"proxyID"`
	Hostname *string `gorm:"column:hostname;type:TEXT" json:"hostname"`
}

// TableName ProxyHost's table name
func (*ProxyHost) TableName() string {
	return TableNameProxyHost
}
