// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelationPredicate = "relationPredicates"

// RelationPredicate mapped from table <relationPredicates>
type RelationPredicate struct {
	PredicateID *int32  `gorm:"column:predicateID;type:INTEGER;primaryKey" json:"predicateID"`
	Predicate   *string `gorm:"column:predicate;type:TEXT" json:"predicate"`
}

// TableName RelationPredicate's table name
func (*RelationPredicate) TableName() string {
	return TableNameRelationPredicate
}
