// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSavedSearch = "savedSearches"

// SavedSearch mapped from table <savedSearches>
type SavedSearch struct {
	SavedSearchID      *int32    `gorm:"column:savedSearchID;type:INTEGER;primaryKey" json:"savedSearchID"`
	SavedSearchName    string    `gorm:"column:savedSearchName;type:TEXT;not null" json:"savedSearchName"`
	ClientDateModified time.Time `gorm:"column:clientDateModified;type:TIMESTAMP;not null;default:CURRENT_TIMESTAMP" json:"clientDateModified"`
	LibraryID          int32     `gorm:"column:libraryID;type:INT;not null" json:"libraryID"`
	Key                string    `gorm:"column:key;type:TEXT;not null" json:"key"`
	Version            int32     `gorm:"column:version;type:INT;not null" json:"version"`
	Synced             int32     `gorm:"column:synced;type:INT;not null;index:savedSearches_synced,priority:1" json:"synced"`
}

// TableName SavedSearch's table name
func (*SavedSearch) TableName() string {
	return TableNameSavedSearch
}
