// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSavedSearchCondition = "savedSearchConditions"

// SavedSearchCondition mapped from table <savedSearchConditions>
type SavedSearchCondition struct {
	SavedSearchID     int32   `gorm:"column:savedSearchID;type:INT;primaryKey" json:"savedSearchID"`
	SearchConditionID int32   `gorm:"column:searchConditionID;type:INT;not null" json:"searchConditionID"`
	Condition         string  `gorm:"column:condition;type:TEXT;not null" json:"condition"`
	Operator          *string `gorm:"column:operator;type:TEXT" json:"operator"`
	Value             *string `gorm:"column:value;type:TEXT" json:"value"`
	Required          *string `gorm:"column:required;type:NONE" json:"required"`
}

// TableName SavedSearchCondition's table name
func (*SavedSearchCondition) TableName() string {
	return TableNameSavedSearchCondition
}
