// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSetting = "settings"

// Setting mapped from table <settings>
type Setting struct {
	Setting *string `gorm:"column:setting;type:TEXT;primaryKey" json:"setting"`
	Key     *string `gorm:"column:key;type:TEXT" json:"key"`
	Value   *string `gorm:"column:value;type" json:"value"`
}

// TableName Setting's table name
func (*Setting) TableName() string {
	return TableNameSetting
}
