// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStorageDeleteLog = "storageDeleteLog"

// StorageDeleteLog mapped from table <storageDeleteLog>
type StorageDeleteLog struct {
	LibraryID   int32  `gorm:"column:libraryID;type:INT;primaryKey" json:"libraryID"`
	Key         string `gorm:"column:key;type:TEXT;not null" json:"key"`
	DateDeleted string `gorm:"column:dateDeleted;type:TEXT;not null;default:CURRENT_TIMESTAMP" json:"dateDeleted"`
}

// TableName StorageDeleteLog's table name
func (*StorageDeleteLog) TableName() string {
	return TableNameStorageDeleteLog
}
