// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSyncObjectType = "syncObjectTypes"

// SyncObjectType mapped from table <syncObjectTypes>
type SyncObjectType struct {
	SyncObjectTypeID *int32  `gorm:"column:syncObjectTypeID;type:INTEGER;primaryKey" json:"syncObjectTypeID"`
	Name             *string `gorm:"column:name;type:TEXT;index:syncObjectTypes_name,priority:1" json:"name"`
}

// TableName SyncObjectType's table name
func (*SyncObjectType) TableName() string {
	return TableNameSyncObjectType
}
