// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSyncQueue = "syncQueue"

// SyncQueue mapped from table <syncQueue>
type SyncQueue struct {
	LibraryID        int32      `gorm:"column:libraryID;type:INT;primaryKey" json:"libraryID"`
	Key              string     `gorm:"column:key;type:TEXT;not null" json:"key"`
	SyncObjectTypeID int32      `gorm:"column:syncObjectTypeID;type:INT;not null" json:"syncObjectTypeID"`
	LastCheck        *time.Time `gorm:"column:lastCheck;type:TIMESTAMP" json:"lastCheck"`
	Tries            *int32     `gorm:"column:tries;type:INT" json:"tries"`
}

// TableName SyncQueue's table name
func (*SyncQueue) TableName() string {
	return TableNameSyncQueue
}
