// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSyncedSetting = "syncedSettings"

// SyncedSetting mapped from table <syncedSettings>
type SyncedSetting struct {
	Setting   string  `gorm:"column:setting;type:TEXT;primaryKey" json:"setting"`
	LibraryID int32   `gorm:"column:libraryID;type:INT;not null" json:"libraryID"`
	Value     *string `gorm:"column:value;type:NOT" json:"value"`
	Version   int32   `gorm:"column:version;type:INT;not null" json:"version"`
	Synced    int32   `gorm:"column:synced;type:INT;not null" json:"synced"`
}

// TableName SyncedSetting's table name
func (*SyncedSetting) TableName() string {
	return TableNameSyncedSetting
}
