// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTranslatorCache = "translatorCache"

// TranslatorCache mapped from table <translatorCache>
type TranslatorCache struct {
	FileName         *string `gorm:"column:fileName;type:TEXT;primaryKey" json:"fileName"`
	MetadataJSON     *string `gorm:"column:metadataJSON;type:TEXT" json:"metadataJSON"`
	LastModifiedTime *int32  `gorm:"column:lastModifiedTime;type:INT" json:"lastModifiedTime"`
}

// TableName TranslatorCache's table name
func (*TranslatorCache) TableName() string {
	return TableNameTranslatorCache
}
