// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	UserID *int32 `gorm:"column:userID;type:INTEGER;primaryKey" json:"userID"`
	Name   string `gorm:"column:name;type:TEXT;not null" json:"name"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
