// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameVersion = "version"

// Version mapped from table <version>
type Version struct {
	Schema  *string `gorm:"column:schema;type:TEXT;primaryKey" json:"schema"`
	Version int32   `gorm:"column:version;type:INT;not null" json:"version"`
}

// TableName Version's table name
func (*Version) TableName() string {
	return TableNameVersion
}
