// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Arch() {
  return window['go']['main']['App']['Arch']();
}

export function Os() {
  return window['go']['main']['App']['Os']();
}
